# Configurações do Banco de Dados

spring.datasource.url=jdbc:postgresql://<seu_host>:<sua_porta>/<seu_database>
spring.datasource.username=<seu_usuario>
spring.datasource.password=<sua_senha>
spring.jpa.hibernate.ddl-auto=<opção_ddl_auto> # Exemplos: none, update, create, create-drop

# Configuração do Token de Segurança
api.security.token.secret=<sua_chave_secreta> # Insira uma chave secreta para geração de JWT
